[package]
name = "self-checkout-client"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
iced = { version = "0.14.0", features = ["advanced", "image"] }
iced_aw = { version = "0.13.1", default-features = false, features = ["spinner"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
nokhwa = { version = "0.10.10", features = ["input-native"] }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "multipart", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.18", features = ["v4"] }
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros", "sync"] }
tokio-tungstenite = { version = "0.30", features = ["rustls-tls-native-roots"] }
futures-util = "0.3"
url = "2"
